import { HiCursorClick } from "react-icons/hi";
export const ReferencesList = [
  {
    title: "1. Open Access Button API",
    icon: <HiCursorClick />,
    url: "https://openaccessbutton.org/api",
    LinkClassName: "reference-link",
    ListItemClassName: "reference-item",
    TextClassName: "reference-link__details",
    text: "Open Access is a publishing model for scholarly/legal communication that makes research information available to readers at no cost. Open Access Button allows users to instantly find and request research articles. With the Open Access Button APITrack this API, users can access papers, manage subscriptions, find Interlibrary Loans, metadata, depositing papers and more.",
  },

  {
    title: "2. Rocket Sign API",
    icon: <HiCursorClick />,
    url: "https://www.rocketlawyer.com/developers.rl",
    LinkClassName: "reference-link",
    ListItemClassName: "reference-item",
    TextClassName: "reference-link__details",
    text: "Rocket Lawyer provides affordable online legal services, free legal documents, and legal advice. The Rocket Sign APITrack this API provides electronic signature Integration into mobile and web applications. The API enables users to send and sign primary and supporting documents in a single request. Methods are available for email invites to the service, creating binders, uploading documents, and more.",
  },

  {
    title: "3. Gravity Legal API",
    icon: <HiCursorClick />,
    url: "https://gravity-legal.com/apidocs/index.html#introduction",
    LinkClassName: "reference-link",
    ListItemClassName: "reference-item",
    TextClassName: "reference-link__details",
    text: "Gravity Legal supports business processes that are specific to legal professionals such as demarcation of payments between operating and trust accounts, transfer of funds from trust to operating accounts and trust reconciliation by matter and more. The Gravity Legal APITrack this API is a RESTful service that allows attorneys or firms to bill clients for services rendered or funds designated for a trust or IOLTA account.",
  },
  {
    title: "4. PatSnap Connect API",
    icon: <HiCursorClick />,
    url: "https://www.patsnap.com/connect-api",
    LinkClassName: "reference-link",
    ListItemClassName: "reference-item",
    TextClassName: "reference-link__details",
    text: "PatSnap provides patent search and intellectual property services. The PatSnap Connect APITrack this API returns data for patents, intellectual property, research and development, strategy and business, and life sciences. The API provides access to over 132,000,000 patents, with data for over 18 million assignees, across 116 patent authorities. Interested developers can contact the provider for API and Documentation access.",
  },
  {
    title: "5. Actionstep API",
    icon: <HiCursorClick />,
    url: "https://www.actionstep.com/resources/actionstep-api",
    LinkClassName: "reference-link",
    ListItemClassName: "reference-item",
    TextClassName: "reference-link__details",
    text: "Actionstep offers legal practice management softoware. The Actionstep APITrack this API enables developers to integrate legal practice workflow features to define the steps, tasks and timing of any process to increase automation. The Actionstep API allows programmatic access to documents and management tools.",
  },
  {
    title: "6. Avvo API",
    icon: <HiCursorClick />,
    url: "http://avvo.github.io/api-doc/",
    LinkClassName: "reference-link",
    ListItemClassName: "reference-item",
    TextClassName: "reference-link__details",
    text: "The Avvo APITrack this API allows developers to access profiles from the Avvo Lawyer & Doctor directory. Avvo profiles contain helpful information including experience, background, disciplinary history, and reviews from patients and clients. Get data such as lawyer name, address, specialties, reviews and more with the API.",
  },
  {
    title: "7. Practice Panther API",
    icon: <HiCursorClick />,
    url: "https://www.practicepanther.com/law-office-software-api/",
    LinkClassName: "reference-link",
    ListItemClassName: "reference-item",
    TextClassName: "reference-link__details",
    text: "PracticePanther provides law practice management software. The Practice Panther APITrack this API enables developers to build an integration between PracticePanther and another application or service, build custom reports and dashboards, and automate workflows and processes or customize PracticePanther for their law firm. Operations include accounts, bank accounts, call logs, custom fields, emails, expenses, invoices, items, payments, and relationships.",
  },
  {
    title: "8. UniCourt Legal Data API",
    icon: <HiCursorClick />,
    url: "https://unicourt.com/features/legal-data-api",
    LinkClassName: "reference-link",
    ListItemClassName: "reference-item",
    TextClassName: "reference-link__details",
    text: "UniCourt provides access to court records and legal analytics. The UniCourt Legal Data APITrack this API enables users to search through millions of Court cases from U.S. State and Federal Courts, access structured legal data of cases, update cases real-time from the court, order court documents and much more. Methods are available for accessing case details including attorneys, dockets, docket download, updating cases, tracking cases, and more.",
  },
  {
    title: "9. Clio API",
    icon: <HiCursorClick />,
    url: "https://app.clio.com/api/v4/documentation",
    LinkClassName: "reference-link",
    ListItemClassName: "reference-item",
    TextClassName: "reference-link__details",
    text: "Clio is a legal practice management system for small to mid-sized law firms. The Clio APITrack this API allows users to access functionality of the system and data stored inside the firm's Clio instance. API methods include functions for managing activities, bills, contacts, matters, tasks and users. Developers can submit suitable applications to the Clio Marketplace where more than 150,000 Clio legal practice management software users can access the applications.",
  },
  {
    title: "10. Open Law API",
    icon: <HiCursorClick />,
    url: "https://docs.openlaw.io/api-client/",
    LinkClassName: "reference-link",
    ListItemClassName: "reference-item",
    TextClassName: "reference-link__details",
    text: "OpenLaw is a universal legal protocol for Blockchains. The OpenLaw APITrack this API returns Blockchain data for legal applications. The REST API can query, save, and change data in an OpenLaw instance. Methods are available for templates, drafts, contacts, users, community activity and more. Head over to the Law category for more APIs, SDKs, and other developer resources.",
  },
];
